### ISSUE TITLE
[FEAT] 공통 컴포넌트 개발

### ISSUE THREAD

**Issue by jaehawilly** [readysetG0/readysetG0-frontend#29]
### 만들고자 하는 기능이 무엇인가요?
컴포넌트 공통화 (화면설계서 중 마커 상세보기 화면 참고 및 구현)

 ### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
 1. 공통 컴포넌트 폴더 구조 구성
 2. [ ] css 적용 (공통 color, ui, etc...)
 3. [ ] 마커 상세보기 화면 구현

 ### 예상 작업 시간
 ex) 1day

**Comment by Oneul1213** [comment]
1. [x] 마커 상세보기 페이지 틀 잡기
2. [x] 컴포넌트 개발 및 화면 배치
3. [x] 공통화 및 디테일 잡기(css, props  등 수정)
